name: DescribeLiveSnapshotConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Action
  type: String
  required: false
  hidden: true
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: SecurityToken
  type: String
  required: false
  hidden: false
  subparameters: []
- name: DomainName
  type: String
  required: true
  hidden: false
  subparameters: []
- name: AppName
  type: String
  required: false
  hidden: false
  subparameters: []
- name: StreamName
  type: String
  required: false
  hidden: false
  subparameters: []
- name: PageNum
  type: Integer
  required: false
  hidden: false
  subparameters: []
- name: PageSize
  type: Integer
  required: false
  hidden: false
  subparameters: []
- name: Order
  type: String
  required: false
  hidden: false
  subparameters: []
