name: ModifyFileCacheExpiredConfig
protocol: HTTP|HTTPS
method: POST|GET
description:
  zh: |2+


    修改文件过期配置


document_id: "27181"
parameters:
- name: AccessKeyId
  position: Query
  type: String
  description:
    zh: 当认证方式为Accesskey时必填，用户需要显式指定，校验签名使用，不指定则不校验签名
  required: false
  hidden: false
- name: Action
  position: Query
  type: String
  description:
    zh: 操作接口名，系统规定参数，取值：ModifyFileCacheExpiredConfig
  required: false
  hidden: true
- name: OwnerId
  position: Query
  type: Long
  description:
    zh: ""
  required: false
  hidden: true
- name: SecurityToken
  position: Query
  type: String
  description:
    zh: ""
  required: false
  hidden: false
- name: DomainName
  position: Query
  type: String
  description:
    zh: 您的加速域名
  required: true
  hidden: false
- name: ConfigID
  position: Query
  type: String
  description:
    zh: 要修改的配置ID
  required: true
  hidden: false
- name: CacheContent
  position: Query
  type: String
  description:
    zh: 填写文件名后缀，逗号分隔
  required: true
  hidden: false
- name: TTL
  position: Query
  type: String
  description:
    zh: 缓存时间设置，单位为秒
  required: true
  hidden: false
- name: Weight
  position: Query
  type: String
  description:
    zh: 此条配置的权重值, 取值范围为1-99, 数值越大, 优先级越高.默认值为1.
  required: false
  hidden: false
