name: SetDynamicConfig
protocol: HTTP|HTTPS
method: POST|GET
description:
  zh: |2+


    全站加速,缓存规则的配置。


document_id: "62851"
parameters:
- name: AccessKeyId
  position: Query
  type: String
  description:
    zh: 当认证方式为Accesskey时必填，用户需要显式指定，校验签名使用，不指定则不校验签名
  required: false
  hidden: false
- name: Action
  position: Query
  type: String
  description:
    zh: 操作接口名，系统规定参数，取值：SetDynamicConfig
  required: false
  hidden: true
- name: OwnerId
  position: Query
  type: Long
  description:
    zh: ""
  required: false
  hidden: true
- name: SecurityToken
  position: Query
  type: String
  description:
    zh: ""
  required: false
  hidden: false
- name: DomainName
  position: Query
  type: String
  description:
    zh: 您的加速域名
  required: true
  hidden: false
- name: DynamicOrigin
  position: Query
  type: String
  description:
    zh: 回源路由scheme，支持http、https和follow。不填时，默认值为http。
  required: false
  hidden: false
- name: StaticType
  position: Query
  type: String
  description:
    zh: '静态加速文件后缀。样例: .*.(jpg¦htmp¦txt)$'
  required: false
  hidden: false
- name: StaticUri
  position: Query
  type: String
  description:
    zh: 静态加速URI。多个空格隔开。样例:#uri:/yyy/gggsssssssss/cxxxxxcc/a.txt
  required: false
  hidden: false
- name: StaticPath
  position: Query
  type: String
  description:
    zh: 静态加速PATH。多个空格隔开。样例:#path:/path/to/no_dynamic_route/.*.one
  required: false
  hidden: false
- name: DynamicCacheControl
  position: Query
  type: String
  description:
    zh: '特殊header头设置。根据Header中的Cache-Control字段，选择是否动态加速。多个空格隔开。样例: no-cache no-store
      private'
  required: false
  hidden: false
