name: SetDynamicConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Action
  type: String
  required: false
  hidden: true
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: SecurityToken
  type: String
  required: false
  hidden: false
  subparameters: []
- name: DomainName
  type: String
  required: true
  hidden: false
  subparameters: []
- name: DynamicOrigin
  type: String
  required: false
  hidden: false
  subparameters: []
- name: StaticType
  type: String
  required: false
  hidden: false
  subparameters: []
- name: StaticUri
  type: String
  required: false
  hidden: false
  subparameters: []
- name: StaticPath
  type: String
  required: false
  hidden: false
  subparameters: []
- name: DynamicCacheControl
  type: String
  required: false
  hidden: false
  subparameters: []
