name: SetErrorPageConfig
protocol: HTTP|HTTPS
method: POST|GET
description:
  zh: |2+


    设置加速域名自定义404错误页面跳转


document_id: "27176"
parameters:
- name: AccessKeyId
  position: Query
  type: String
  description:
    zh: 当认证方式为Accesskey时必填，用户需要显式指定，校验签名使用，不指定则不校验签名
  required: false
  hidden: false
- name: Action
  position: Query
  type: String
  description:
    zh: 操作接口名，系统规定参数，取值：SetErrorPageConfig
  required: false
  hidden: true
- name: OwnerId
  position: Query
  type: Long
  description:
    zh: ""
  required: false
  hidden: true
- name: SecurityToken
  position: Query
  type: String
  description:
    zh: ""
  required: false
  hidden: false
- name: DomainName
  position: Query
  type: String
  description:
    zh: 您的加速域名
  required: true
  hidden: false
- name: PageType
  position: Query
  type: String
  description:
    zh: 错误页面类型； 取值：default：默认页面；charity：公益页面；other：自定义页面
  required: true
  hidden: false
- name: CustomPageUrl
  position: Query
  type: String
  description:
    zh: 自定义发生错误后跳转到页面URL（该加速域名下的完整路径）
  required: false
  hidden: false
