name: SetForceRedirectConfig
protocol: HTTP|HTTPS
method: POST|GET
description:
  zh: |2+


    设置强制访问跳转方式, 目前支持强制Http或Https跳转.

    注意：
        只有已经上传证书, 且证书被启用的情况下, 才能打开强制跳转功能.

document_id: "27177"
parameters:
- name: AccessKeyId
  position: Query
  type: String
  description:
    zh: 当认证方式为Accesskey时必填，用户需要显式指定，校验签名使用，不指定则不校验签名
  required: false
  hidden: false
- name: Action
  position: Query
  type: String
  description:
    zh: 操作接口名，系统规定参数，取值：SetForceRedirectConfig
  required: false
  hidden: true
- name: OwnerId
  position: Query
  type: Long
  description:
    zh: ""
  required: false
  hidden: true
- name: SecurityToken
  position: Query
  type: String
  description:
    zh: ""
  required: false
  hidden: false
- name: DomainName
  position: Query
  type: String
  description:
    zh: 加速域名
  required: true
  hidden: false
- name: RedirectType
  position: Query
  type: String
  description:
    zh: '强制跳转类型, 取值: Off, Http, Https'
  required: true
  hidden: false
