name: SetForwardSchemeConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: Action
  type: String
  required: false
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  subparameters: []
- name: SecurityToken
  type: String
  required: false
  subparameters: []
- name: Enable
  type: String
  required: true
  subparameters: []
- name: DomainName
  type: String
  required: true
  subparameters: []
- name: SchemeOrigin
  type: String
  required: true
  subparameters: []
- name: SchemeOriginPort
  type: String
  required: true
  subparameters: []
