name: SetIpBlackListConfig
protocol: HTTP|HTTPS
method: POST|GET
description:
  zh: |2+


    设置加速域名的IP黑名单

    注意：

    * IP黑名单当前支持ip网段添加，例如127.0.0.1/24
    > 例如：127.0.0.1/24 24表示采用子网掩码中的前24位为有效位，即用32-24=8bit来表示主机号，该子网可以容纳2^8 - 2 = 254 台主机。故127.0.0.1/24 表示IP网段范围是：127.0.0.1~127.0.0.255

document_id: "55792"
parameters:
- name: AccessKeyId
  position: Query
  type: String
  description:
    zh: 当认证方式为Accesskey时必填，用户需要显式指定，校验签名使用，不指定则不校验签名
  required: false
  hidden: false
- name: Action
  position: Query
  type: String
  description:
    zh: 操作接口名，系统规定参数，取值：SetIpBlackListConfig
  required: false
  hidden: true
- name: OwnerId
  position: Query
  type: Long
  description:
    zh: ""
  required: false
  hidden: true
- name: SecurityToken
  position: Query
  type: String
  description:
    zh: ""
  required: false
  hidden: false
- name: DomainName
  position: Query
  type: String
  description:
    zh: 您的加速域名
  required: true
  hidden: false
- name: BlockIps
  position: Query
  type: String
  description:
    zh: IP黑名单，表示此IP列表禁止访问，IP列表多个用逗号隔开
  required: true
  hidden: false
