name: SetIgnoreQueryStringConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Action
  type: String
  required: false
  hidden: true
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: SecurityToken
  type: String
  required: false
  hidden: false
  subparameters: []
- name: DomainName
  type: String
  required: true
  hidden: false
  subparameters: []
- name: Enable
  type: String
  required: true
  hidden: false
  subparameters: []
- name: HashKeyArgs
  type: String
  required: false
  hidden: false
  subparameters: []
- name: KeepOssArgs
  type: String
  required: false
  hidden: false
  subparameters: []
