name: SetRefererConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Action
  type: String
  required: false
  hidden: true
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: SecurityToken
  type: String
  required: false
  hidden: false
  subparameters: []
- name: DomainName
  type: String
  required: true
  hidden: false
  subparameters: []
- name: ReferType
  type: String
  required: true
  hidden: false
  subparameters: []
- name: ReferList
  type: String
  required: false
  hidden: false
  subparameters: []
- name: AllowEmpty
  type: String
  required: false
  hidden: false
  subparameters: []
- name: DisableAst
  type: String
  required: false
  hidden: false
  subparameters: []
