name: SetRemoteReqAuthConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: Action
  type: String
  required: false
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  subparameters: []
- name: SecurityToken
  type: String
  required: false
  subparameters: []
- name: DomainName
  type: String
  required: true
  subparameters: []
- name: AuthType
  type: String
  required: true
  subparameters: []
- name: TimeOut
  type: String
  required: true
  subparameters: []
- name: AuthAddr
  type: String
  required: true
  subparameters: []
- name: AuthCrash
  type: String
  required: true
  subparameters: []
- name: AuthEnable
  type: String
  required: true
  subparameters: []
- name: AuthProvider
  type: String
  required: true
  subparameters: []
- name: AuthPath
  type: String
  required: false
  subparameters: []
- name: AuthFileType
  type: String
  required: false
  subparameters: []
