name: SetReqHeaderConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Action
  type: String
  required: false
  hidden: true
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: SecurityToken
  type: String
  required: false
  hidden: false
  subparameters: []
- name: DomainName
  type: String
  required: true
  hidden: false
  subparameters: []
- name: Key
  type: String
  required: true
  hidden: false
  subparameters: []
- name: Value
  type: String
  required: true
  hidden: false
  subparameters: []
- name: ConfigId
  type: Long
  required: false
  hidden: false
  subparameters: []
