name: SetReqAuthConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: Action
  type: String
  required: false
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  subparameters: []
- name: SecurityToken
  type: String
  required: false
  subparameters: []
- name: DomainName
  type: String
  required: true
  subparameters: []
- name: AuthType
  type: String
  required: true
  subparameters: []
- name: Key1
  type: String
  required: false
  subparameters: []
- name: Key2
  type: String
  required: false
  subparameters: []
- name: TimeOut
  type: String
  required: false
  subparameters: []
- name: AuthRemoteDesc
  type: String
  required: false
  subparameters: []
