name: SetRefererConfig
protocol: HTTP|HTTPS
method: POST|GET
description:
  zh: |+
    设置加速域名的Refer防盗链功能


document_id: "27178"
parameters:
- name: AccessKeyId
  position: Query
  type: String
  description:
    zh: 当认证方式为Accesskey时必填，用户需要显式指定，校验签名使用，不指定则不校验签名
  required: false
  hidden: false
- name: Action
  position: Query
  type: String
  description:
    zh: 操作接口名，系统规定参数，取值：SetRefererConfig
  required: false
  hidden: true
- name: OwnerId
  position: Query
  type: Long
  description:
    zh: ""
  required: false
  hidden: true
- name: SecurityToken
  position: Query
  type: String
  description:
    zh: ""
  required: false
  hidden: false
- name: DomainName
  position: Query
  type: String
  description:
    zh: 您的加速域名
  required: true
  hidden: false
- name: ReferType
  position: Query
  type: String
  description:
    zh: refer类型，取值：block：黑名单；allow：白名单
  required: true
  hidden: false
- name: ReferList
  position: Query
  type: String
  description:
    zh: 逗号隔开的域名列表
  required: false
  hidden: false
- name: AllowEmpty
  position: Query
  type: String
  description:
    zh: 是否允许空refer访问,取值：on：允许；off：不允许；默认值：on
  required: false
  hidden: false
- name: DisableAst
  position: Query
  type: String
  description:
    zh: 是否精确匹配域名，取值：on：精确匹配，不自动匹配子域名；off：模糊匹配，自动匹配子域名；默认值：off
  required: false
  hidden: false
