name: SetWaitingRoomConfig
protocol: HTTP|HTTPS
method: GET
description: {}
document_id: ""
parameters:
- name: AccessKeyId
  position: Query
  type: String
  required: false
  hidden: false
- name: Action
  position: Query
  type: String
  required: false
  hidden: true
- name: Version
  position: Query
  type: String
  required: false
  hidden: false
- name: OwnerId
  position: Query
  type: Long
  required: false
  hidden: true
- name: SecurityToken
  position: Query
  type: String
  required: false
  hidden: false
- name: DomainName
  position: Query
  type: String
  required: true
  hidden: false
- name: WaitUri
  position: Query
  type: String
  required: true
  hidden: false
- name: AllowPct
  position: Query
  type: Integer
  required: true
  hidden: false
- name: MaxTimeWait
  position: Query
  type: Integer
  required: true
  hidden: false
- name: GapTime
  position: Query
  type: Integer
  required: true
  hidden: false
- name: WaitUrl
  position: Query
  type: String
  required: true
  hidden: false
- name: MaxQps
  position: Query
  type: Long
  required: false
  hidden: false
