name: UpdateLiveAppSnapshotConfig
protocol: HTTP|HTTPS
method: POST|GET
description: {}
document_id: ""
parameters:
- name: AccessKeyId
  position: Query
  type: String
  required: false
  hidden: false
- name: Action
  position: Query
  type: String
  required: false
  hidden: true
- name: OwnerId
  position: Query
  type: Long
  required: false
  hidden: true
- name: SecurityToken
  position: Query
  type: String
  required: false
  hidden: false
- name: DomainName
  position: Query
  type: String
  required: true
  hidden: false
- name: AppName
  position: Query
  type: String
  required: true
  hidden: false
- name: TimeInterval
  position: Query
  type: Integer
  required: false
  hidden: false
- name: OssEndpoint
  position: Query
  type: String
  required: false
  hidden: false
- name: OssBucket
  position: Query
  type: String
  required: false
  hidden: false
- name: OverwriteOssObject
  position: Query
  type: String
  required: false
  hidden: false
- name: SequenceOssObject
  position: Query
  type: String
  required: false
  hidden: false
