name: AddLiveDetectNotifyConfig
protocol: HTTP|HTTPS
method: POST|GET
description:
  zh: |2+

    添加回调通知 URL。

document_id: "56039"
parameters:
- name: AccessKeyId
  position: Query
  type: String
  description:
    zh: 当认证方式为Accesskey时必填，用户需要显式指定，校验签名使用，不指定则不校验签名
  required: false
  hidden: false
- name: Action
  position: Query
  type: String
  description:
    zh: 系统规定参数，取值：AddLiveDetectNotifyConfig
  required: false
  hidden: true
- name: SecurityToken
  position: Query
  type: String
  description:
    zh: ""
  required: false
  hidden: false
- name: OwnerId
  position: Query
  type: Long
  description:
    zh: ""
  required: false
  hidden: true
- name: DomainName
  position: Query
  type: String
  description:
    zh: 用户域名
  required: true
  hidden: false
- name: NotifyUrl
  position: Query
  type: String
  description:
    zh: 发现涉黄涉政等违规内容的回调函数
  required: true
  hidden: false
