name: AddLiveAppSnapshotConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: Action
  type: String
  required: false
  subparameters: []
- name: SecurityToken
  type: String
  required: false
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  subparameters: []
- name: DomainName
  type: String
  required: true
  subparameters: []
- name: AppName
  type: String
  required: true
  subparameters: []
- name: TimeInterval
  type: Integer
  required: true
  subparameters: []
- name: OssEndpoint
  type: String
  required: true
  subparameters: []
- name: OssBucket
  type: String
  required: true
  subparameters: []
- name: OverwriteOssObject
  type: String
  required: false
  subparameters: []
- name: SequenceOssObject
  type: String
  required: false
  subparameters: []
