name: AddLiveAppRecordConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Action
  type: String
  required: false
  hidden: true
  subparameters: []
- name: SecurityToken
  type: String
  required: false
  hidden: false
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: DomainName
  type: String
  required: true
  hidden: false
  subparameters: []
- name: AppName
  type: String
  required: true
  hidden: false
  subparameters: []
- name: OssEndpoint
  type: String
  required: true
  hidden: false
  subparameters: []
- name: OssBucket
  type: String
  required: true
  hidden: false
  subparameters: []
- name: RecordFormat
  type: RepeatList
  required: true
  hidden: false
  subparameters:
  - name: Format
    type: String
    required: false
    hidden: false
    subparameters: []
  - name: OssObjectPrefix
    type: String
    required: false
    hidden: false
    subparameters: []
  - name: SliceOssObjectPrefix
    type: String
    required: false
    hidden: false
    subparameters: []
  - name: CycleDuration
    type: Integer
    required: false
    hidden: false
    subparameters: []
