name: DescribeLiveSnapshotDetectPornConfig
protocol: HTTP|HTTPS
method: POST|GET
description:
  zh: |2+

    查询审核配置。

document_id: "56044"
parameters:
- name: AccessKeyId
  position: Query
  type: String
  description:
    zh: 当认证方式为Accesskey时必填，用户需要显式指定，校验签名使用，不指定则不校验签名
  required: false
  hidden: false
- name: Action
  position: Query
  type: String
  description:
    zh: 系统规定参数，取值：DescribeLiveSnapshotDetectPornConfig
  required: false
  hidden: true
- name: SecurityToken
  position: Query
  type: String
  description:
    zh: ""
  required: false
  hidden: false
- name: OwnerId
  position: Query
  type: Long
  description:
    zh: ""
  required: false
  hidden: true
- name: DomainName
  position: Query
  type: String
  description:
    zh: 用户域名
  required: true
  hidden: false
- name: AppName
  position: Query
  type: String
  description:
    zh: app名，如不给出表示域名下所有的
  required: false
  hidden: false
- name: PageNum
  position: Query
  type: Integer
  description:
    zh: '分页的页码，默认值：1 '
  required: false
  hidden: false
- name: PageSize
  position: Query
  type: Integer
  description:
    zh: '每页大小，默认值：10，范围：\[5,30] '
  required: false
  hidden: false
- name: Order
  position: Query
  type: String
  description:
    zh: '排序，asc：升序，desc：降序，默认：asc '
  required: false
  hidden: false
