name: DescribeLiveStreamsNotifyUrlConfig
protocol: HTTP|HTTPS
method: POST|GET
description:
  zh: |+
    查询推流回调配置。


document_id: "51835"
parameters:
- name: AccessKeyId
  position: Query
  type: String
  description:
    zh: 当认证方式为Accesskey时必填，用户需要显式指定，校验签名使用，不指定则不校验签名
  required: false
  hidden: false
- name: Action
  position: Query
  type: String
  description:
    zh: 系统规定参数，取值：DescribeLiveStreamsNotifyUrlConfig
  required: false
  hidden: true
- name: SecurityToken
  position: Query
  type: String
  description:
    zh: ""
  required: false
  hidden: false
- name: OwnerId
  position: Query
  type: Long
  description:
    zh: ""
  required: false
  hidden: true
- name: DomainName
  position: Query
  type: String
  description:
    zh: 您的加速域名
  required: true
  hidden: false
