name: DescribeLiveMixNotifyConfig
protocol: HTTP|HTTPS
method: POST|GET
description: {}
document_id: ""
parameters:
- name: AccessKeyId
  position: Query
  type: String
  required: false
  hidden: false
- name: Action
  position: Query
  type: String
  required: false
  hidden: true
- name: SecurityToken
  position: Query
  type: String
  required: false
  hidden: false
- name: OwnerId
  position: Query
  type: Long
  required: false
  hidden: true
- name: DomainName
  position: Query
  type: String
  required: true
  hidden: false
