name: DescribeCasterConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Action
  type: String
  required: false
  hidden: true
  subparameters: []
- name: Version
  type: String
  required: false
  hidden: false
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: SecurityToken
  type: String
  required: false
  hidden: false
  subparameters: []
- name: CasterId
  type: String
  required: true
  hidden: false
  subparameters: []
