name: SetCasterConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Action
  type: String
  required: false
  hidden: true
  subparameters: []
- name: Version
  type: String
  required: false
  hidden: false
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: SecurityToken
  type: String
  required: false
  hidden: false
  subparameters: []
- name: CasterId
  type: String
  required: true
  hidden: false
  subparameters: []
- name: CasterName
  type: String
  required: false
  hidden: false
  subparameters: []
- name: DomainName
  type: String
  required: false
  hidden: false
  subparameters: []
- name: TranscodeConfig
  type: String
  required: false
  hidden: false
  subparameters: []
- name: RecordConfig
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Delay
  type: Float
  required: false
  hidden: false
  subparameters: []
- name: UrgentMaterialId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: SideOutputUrl
  type: String
  required: false
  hidden: false
  subparameters: []
- name: CallbackUrl
  type: String
  required: false
  hidden: false
  subparameters: []
