name: UpdateLiveRecordNotifyConfig
protocol: HTTP|HTTPS
method: POST|GET
description:
  zh: |2+


    更新域名级别录制回调配置。


document_id: "51832"
parameters:
- name: AccessKeyId
  position: Query
  type: String
  description:
    zh: 当认证方式为Accesskey时必填，用户需要显式指定，校验签名使用，不指定则不校验签名
  required: false
  hidden: false
- name: Action
  position: Query
  type: String
  description:
    zh: 系统规定参数，取值：UpdateLiveRecordNotifyConfig
  required: false
  hidden: true
- name: SecurityToken
  position: Query
  type: String
  description:
    zh: ""
  required: false
  hidden: false
- name: OwnerId
  position: Query
  type: Long
  description:
    zh: ""
  required: false
  hidden: true
- name: DomainName
  position: Query
  type: String
  description:
    zh: 加速域名
  required: true
  hidden: false
- name: NotifyUrl
  position: Query
  type: String
  description:
    zh: 回调url地址，必须以’http://‘ 或 ‘https://‘ 开头，需要做 url encode
  required: false
  hidden: false
- name: NeedStatusNotify
  position: Query
  type: Boolean
  description:
    zh: 是否需要录制任务状态回调，可取值true/false, 默认 false
  required: false
  hidden: false
