name: UpdateCasterSceneConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: Action
  type: String
  required: false
  subparameters: []
- name: Version
  type: String
  required: false
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  subparameters: []
- name: SecurityToken
  type: String
  required: false
  subparameters: []
- name: CasterId
  type: String
  required: true
  subparameters: []
- name: SceneId
  type: String
  required: true
  subparameters: []
- name: LayoutId
  type: String
  required: true
  subparameters: []
- name: ComponentId
  type: RepeatList
  required: false
  subparameters: []
