name: UpdateLiveSnapshotDetectPornConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Action
  type: String
  required: false
  hidden: true
  subparameters: []
- name: SecurityToken
  type: String
  required: false
  hidden: false
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: DomainName
  type: String
  required: true
  hidden: false
  subparameters: []
- name: AppName
  type: String
  required: true
  hidden: false
  subparameters: []
- name: OssEndpoint
  type: String
  required: false
  hidden: false
  subparameters: []
- name: OssBucket
  type: String
  required: false
  hidden: false
  subparameters: []
- name: OssObject
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Interval
  type: Integer
  required: false
  hidden: false
  subparameters: []
- name: Scene
  type: RepeatList
  required: false
  hidden: false
  subparameters: []
