name: CreateScalingConfiguration
parameters:
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: Action
  type: String
  required: false
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  subparameters: []
- name: ResourceOwnerAccount
  type: String
  required: false
  subparameters: []
- name: ScalingGroupId
  type: String
  required: true
  subparameters: []
- name: ImageId
  type: String
  required: true
  subparameters: []
- name: InstanceType
  type: String
  required: false
  subparameters: []
- name: InstanceTypes
  type: RepeatList
  required: false
  subparameters: []
- name: SecurityGroupId
  type: String
  required: true
  subparameters: []
- name: IoOptimized
  type: String
  required: false
  subparameters: []
- name: InternetChargeType
  type: String
  required: false
  subparameters: []
- name: InternetMaxBandwidthIn
  type: Integer
  required: false
  subparameters: []
- name: InternetMaxBandwidthOut
  type: Integer
  required: false
  subparameters: []
- name: SystemDisk.Category
  type: String
  required: false
  subparameters: []
- name: SystemDisk.Size
  type: Integer
  required: false
  subparameters: []
- name: ScalingConfigurationName
  type: String
  required: false
  subparameters: []
- name: DataDisk.1.Size
  type: Integer
  required: false
  subparameters: []
- name: DataDisk.2.Size
  type: Integer
  required: false
  subparameters: []
- name: DataDisk.3.Size
  type: Integer
  required: false
  subparameters: []
- name: DataDisk.4.Size
  type: Integer
  required: false
  subparameters: []
- name: DataDisk.1.Category
  type: String
  required: false
  subparameters: []
- name: DataDisk.2.Category
  type: String
  required: false
  subparameters: []
- name: DataDisk.3.Category
  type: String
  required: false
  subparameters: []
- name: DataDisk.4.Category
  type: String
  required: false
  subparameters: []
- name: DataDisk.1.SnapshotId
  type: String
  required: false
  subparameters: []
- name: DataDisk.2.SnapshotId
  type: String
  required: false
  subparameters: []
- name: DataDisk.3.SnapshotId
  type: String
  required: false
  subparameters: []
- name: DataDisk.4.SnapshotId
  type: String
  required: false
  subparameters: []
- name: DataDisk.1.Device
  type: String
  required: false
  subparameters: []
- name: DataDisk.2.Device
  type: String
  required: false
  subparameters: []
- name: DataDisk.3.Device
  type: String
  required: false
  subparameters: []
- name: DataDisk.4.Device
  type: String
  required: false
  subparameters: []
- name: DataDisk.1.DeleteWithInstance
  type: String
  required: false
  subparameters: []
- name: DataDisk.2.DeleteWithInstance
  type: String
  required: false
  subparameters: []
- name: DataDisk.3.DeleteWithInstance
  type: String
  required: false
  subparameters: []
- name: DataDisk.4.DeleteWithInstance
  type: String
  required: false
  subparameters: []
- name: LoadBalancerWeight
  type: Integer
  required: false
  subparameters: []
- name: OwnerAccount
  type: String
  required: false
  subparameters: []
- name: Tags
  type: String
  required: false
  subparameters: []
- name: UserData
  type: String
  required: false
  subparameters: []
- name: KeyPairName
  type: String
  required: false
  subparameters: []
- name: RamRoleName
  type: String
  required: false
  subparameters: []
- name: SecurityEnhancementStrategy
  type: String
  required: false
  subparameters: []
- name: InstanceName
  type: String
  required: false
  subparameters: []
