name: CreateLogConfig
protocol: HTTPS|HTTP
method: POST|GET
description: {}
document_id: ""
parameters:
- name: RegionId
  position: Host
  type: String
  required: false
  hidden: false
- name: SlsProject
  position: Query
  type: String
  required: true
  hidden: false
- name: SlsLogStore
  position: Query
  type: String
  required: true
  hidden: false
- name: LogType
  position: Query
  type: String
  required: false
  hidden: false
