name: DescribeLogConfig
parameters:
- name: RegionId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: LogType
  type: String
  required: false
  hidden: false
  subparameters: []
