name: DescribeAppSecurity
parameters:
- name: Action
  type: String
  required: false
  hidden: true
  subparameters: []
- name: AppId
  type: Long
  required: true
  hidden: false
  subparameters: []
