name: AddApgroupConfig
protocol: HTTP|HTTPS
method: POST|GET
description: {}
document_id: ""
parameters:
- name: AccessKeyId
  position: Query
  type: String
  required: false
  hidden: false
- name: Name
  position: Query
  type: String
  required: true
  hidden: false
- name: ParentApgroupId
  position: Query
  type: Long
  required: true
  hidden: false
- name: Description
  position: Query
  type: String
  required: false
  hidden: false
