name: DeleteApRadioSsidConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Id
  type: Long
  required: true
  hidden: false
  subparameters: []
- name: InstantlyEffective
  type: Integer
  required: false
  hidden: false
  subparameters: []
