name: ListConfigByAction
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: ActionName
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Limit
  type: Integer
  required: false
  hidden: false
  subparameters: []
- name: SearchName
  type: String
  required: false
  hidden: false
  subparameters: []
