name: ListGroupApBriefConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: PageIndex
  type: Integer
  required: true
  subparameters: []
- name: Length
  type: Integer
  required: true
  subparameters: []
- name: OrderCol
  type: String
  required: true
  subparameters: []
- name: OrderDir
  type: String
  required: true
  subparameters: []
- name: ApgroupId
  type: Long
  required: true
  subparameters: []
- name: ColCnt
  type: Integer
  required: true
  subparameters: []
- name: SearchMac
  type: String
  required: false
  subparameters: []
- name: SearchName
  type: String
  required: false
  subparameters: []
