name: ListBriefApConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: SearchMac
  type: String
  required: false
  subparameters: []
- name: SearchName
  type: String
  required: false
  subparameters: []
- name: SearchScan
  type: Integer
  required: false
  subparameters: []
- name: SearchModel
  type: String
  required: false
  subparameters: []
- name: PageIndex
  type: Integer
  required: true
  subparameters: []
- name: Length
  type: Integer
  required: true
  subparameters: []
- name: OrderCol
  type: String
  required: false
  subparameters: []
- name: OrderDir
  type: String
  required: false
  subparameters: []
