name: ListConfigByAction
protocol: HTTP|HTTPS
method: POST|GET
description: {}
document_id: ""
parameters:
- name: AccessKeyId
  position: Query
  type: String
  required: false
  hidden: false
- name: ActionName
  position: Query
  type: String
  required: false
  hidden: false
- name: Limit
  position: Query
  type: Integer
  required: false
  hidden: false
- name: SearchName
  position: Query
  type: String
  required: false
  hidden: false
