name: SaveApPortalConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: PortalStatus
  type: Boolean
  required: true
  hidden: false
  subparameters: []
- name: PortalUrl
  type: String
  required: true
  hidden: false
  subparameters: []
- name: AuthKey
  type: String
  required: false
  hidden: false
  subparameters: []
- name: AuthSecret
  type: String
  required: false
  hidden: false
  subparameters: []
- name: WebAuthUrl
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Whitelist
  type: String
  required: false
  hidden: false
  subparameters: []
- name: CheckUrl
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Network
  type: Integer
  required: false
  hidden: false
  subparameters: []
- name: ApConfigId
  type: Long
  required: true
  hidden: false
  subparameters: []
