name: SaveApgroupConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Id
  type: Long
  required: true
  hidden: false
  subparameters: []
- name: Name
  type: String
  required: true
  hidden: false
  subparameters: []
- name: EchoInt
  type: Integer
  required: true
  hidden: false
  subparameters: []
- name: Country
  type: String
  required: true
  hidden: false
  subparameters: []
- name: Dai
  type: String
  required: false
  hidden: false
  subparameters: []
- name: LogIp
  type: String
  required: false
  hidden: false
  subparameters: []
- name: LogLevel
  type: Integer
  required: false
  hidden: false
  subparameters: []
- name: Description
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Scan
  type: Integer
  required: false
  hidden: false
  subparameters: []
