name: SaveApgroupSsidConfig
protocol: HTTP|HTTPS
method: POST|GET
description: {}
document_id: ""
parameters:
- name: AccessKeyId
  position: Query
  type: String
  required: false
  hidden: false
- name: JsonData
  position: Query
  type: String
  required: true
  hidden: false
