name: SaveAccountConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: JsonData
  type: String
  required: true
  hidden: false
  subparameters: []
