name: SaveApgroupScanConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: ApgroupId
  type: Long
  required: true
  subparameters: []
- name: JsonData
  type: String
  required: false
  subparameters: []
