name: SaveApRadioConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: Id
  type: Long
  required: true
  subparameters: []
- name: Hwmode
  type: String
  required: true
  subparameters: []
- name: Htmode
  type: String
  required: true
  subparameters: []
- name: Channel
  type: Integer
  required: true
  subparameters: []
- name: Txpower
  type: Integer
  required: true
  subparameters: []
- name: BeaconInt
  type: Integer
  required: true
  subparameters: []
- name: Rts
  type: Integer
  required: true
  subparameters: []
- name: Frag
  type: Integer
  required: true
  subparameters: []
- name: Shortgi
  type: Integer
  required: true
  subparameters: []
- name: Probereq
  type: Integer
  required: true
  subparameters: []
- name: Noscan
  type: Integer
  required: true
  subparameters: []
- name: Minrate
  type: Integer
  required: true
  subparameters: []
- name: BcastRate
  type: Integer
  required: true
  subparameters: []
- name: McastRate
  type: Integer
  required: false
  subparameters: []
- name: Uapsd
  type: Integer
  required: true
  subparameters: []
- name: Disabled
  type: Integer
  required: true
  subparameters: []
- name: RadioIndex
  type: Integer
  required: true
  subparameters: []
- name: RequireMode
  type: String
  required: false
  subparameters: []
- name: Mac
  type: String
  required: false
  subparameters: []
- name: InstantlyEffective
  type: Integer
  required: false
  subparameters: []
