name: SaveApRadioSsidConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: Id
  type: Long
  required: false
  subparameters: []
- name: Ssid
  type: String
  required: true
  subparameters: []
- name: ApAssetId
  type: Long
  required: true
  subparameters: []
- name: EncKey
  type: String
  required: false
  subparameters: []
- name: SsidLb
  type: Integer
  required: true
  subparameters: []
- name: DisassocWeakRssi
  type: Integer
  required: true
  subparameters: []
- name: IgnoreWeakProbe
  type: Integer
  required: true
  subparameters: []
- name: Encryption
  type: String
  required: true
  subparameters: []
- name: Disabled
  type: Integer
  required: true
  subparameters: []
- name: Maxassoc
  type: Integer
  required: true
  subparameters: []
- name: Hidden
  type: Integer
  required: true
  subparameters: []
- name: ShortPreamble
  type: Integer
  required: true
  subparameters: []
- name: DisassocLowAck
  type: Integer
  required: true
  subparameters: []
- name: Isolate
  type: Integer
  required: true
  subparameters: []
- name: Wmm
  type: Integer
  required: true
  subparameters: []
- name: AuthCache
  type: Integer
  required: true
  subparameters: []
- name: MaxInactivity
  type: Integer
  required: true
  subparameters: []
- name: Ieee80211w
  type: Integer
  required: true
  subparameters: []
- name: DynamicVlan
  type: Integer
  required: true
  subparameters: []
- name: VlanDhcp
  type: Integer
  required: true
  subparameters: []
- name: MulticastForward
  type: Integer
  required: true
  subparameters: []
- name: Cir
  type: Integer
  required: false
  subparameters: []
- name: Network
  type: Integer
  required: true
  subparameters: []
- name: Mac
  type: String
  required: true
  subparameters: []
- name: RadioIndex
  type: Integer
  required: true
  subparameters: []
- name: InstantlyEffective
  type: Integer
  required: false
  subparameters: []
- name: AuthServer
  type: String
  required: false
  subparameters: []
- name: AuthPort
  type: Integer
  required: false
  subparameters: []
- name: AuthSecret
  type: String
  required: false
  subparameters: []
- name: AcctServer
  type: String
  required: false
  subparameters: []
- name: AcctPort
  type: Integer
  required: false
  subparameters: []
- name: AcctSecret
  type: String
  required: false
  subparameters: []
- name: SecondaryAuthServer
  type: String
  required: false
  subparameters: []
- name: SecondaryAuthPort
  type: Integer
  required: false
  subparameters: []
- name: SecondaryAuthSecret
  type: String
  required: false
  subparameters: []
- name: SecondaryAcctServer
  type: String
  required: false
  subparameters: []
- name: SecondaryAcctPort
  type: Integer
  required: false
  subparameters: []
- name: SecondaryAcctSecret
  type: String
  required: false
  subparameters: []
- name: Nasid
  type: String
  required: false
  subparameters: []
- name: Ownip
  type: String
  required: false
  subparameters: []
- name: DaeClient
  type: String
  required: false
  subparameters: []
- name: DaePort
  type: Integer
  required: false
  subparameters: []
- name: DaeSecret
  type: String
  required: false
  subparameters: []
