name: ProduceEditingProjectVideo
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Action
  type: String
  required: false
  hidden: true
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: ResourceOwnerAccount
  type: String
  required: false
  hidden: true
  subparameters: []
- name: ResourceOwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: ProjectId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Timeline
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Title
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Description
  type: String
  required: false
  hidden: false
  subparameters: []
- name: CoverURL
  type: String
  required: false
  hidden: false
  subparameters: []
