name: ProduceEditingProjectVideo
protocol: HTTP|HTTPS
method: POST|GET
description: {}
document_id: ""
parameters:
- name: AccessKeyId
  position: Query
  type: String
  required: false
  hidden: false
- name: Action
  position: Query
  type: String
  required: false
  hidden: true
- name: OwnerId
  position: Query
  type: Long
  required: false
  hidden: true
- name: ResourceOwnerAccount
  position: Query
  type: String
  required: false
  hidden: true
- name: ResourceOwnerId
  position: Query
  type: Long
  required: false
  hidden: true
- name: ProjectId
  position: Query
  type: String
  required: false
  hidden: false
- name: Timeline
  position: Query
  type: String
  required: false
  hidden: false
- name: Title
  position: Query
  type: String
  required: false
  hidden: false
- name: Description
  position: Query
  type: String
  required: false
  hidden: false
- name: CoverURL
  position: Query
  type: String
  required: false
  hidden: false
