name: ProductInfoComplement
parameters:
- name: name
  type: String
  required: true
  hidden: false
  subparameters: []
- name: gender
  type: String
  required: true
  hidden: false
  subparameters: []
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
