name: DescribeMacConfig
protocol: HTTP|HTTPS
method: POST|GET
description: {}
document_id: ""
parameters:
- name: SourceIp
  position: Query
  type: String
  required: false
  hidden: false
- name: ResourceOwnerId
  position: Query
  type: Long
  required: false
  hidden: true
- name: Target
  position: Query
  type: String
  required: false
  hidden: false
- name: Types
  position: Query
  type: String
  required: false
  hidden: false
- name: Type
  position: Query
  type: String
  required: false
  hidden: false
- name: Config
  position: Query
  type: String
  required: false
  hidden: false
- name: Extern
  position: Query
  type: String
  required: false
  hidden: false
