name: DescribeBackupSetsForSecurity
parameters:
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: Action
  type: String
  required: false
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  subparameters: []
- name: ResourceOwnerAccount
  type: String
  required: false
  subparameters: []
- name: ResourceOwnerId
  type: Long
  required: false
  subparameters: []
- name: DBInstanceId
  type: String
  required: true
  subparameters: []
- name: TargetAliUid
  type: String
  required: false
  subparameters: []
- name: TargetAliBid
  type: String
  required: false
  subparameters: []
- name: BackupId
  type: String
  required: false
  subparameters: []
- name: BackupLocation
  type: String
  required: false
  subparameters: []
- name: BackupStatus
  type: String
  required: false
  subparameters: []
- name: BackupMode
  type: String
  required: false
  subparameters: []
- name: StartTime
  type: String
  required: true
  subparameters: []
- name: EndTime
  type: String
  required: true
  subparameters: []
- name: PageSize
  type: Integer
  required: false
  subparameters: []
- name: PageNumber
  type: Integer
  required: false
  subparameters: []
- name: OwnerAccount
  type: String
  required: false
  subparameters: []
