name: ModifyDBInstanceHAConfig
protocol: HTTP|HTTPS
method: POST|GET
description:
  zh: "\n\n修改实例的数据复制模式和高可用切换策略。  \n  \n"
document_id: "26250"
parameters:
- name: AccessKeyId
  position: Query
  type: String
  description:
    zh: 阿里云颁发给用户的访问服务所用的密钥ID。
  required: false
  hidden: false
- name: AccessKeyId
  position: Query
  type: String
  required: false
  hidden: false
- name: Action
  position: Query
  type: String
  description:
    zh: 系统规定参数，取值：ModifyDBInstanceHAConfig。
  required: false
  hidden: true
- name: OwnerId
  position: Query
  type: Long
  description:
    zh: ""
  required: false
  hidden: true
- name: ResourceOwnerAccount
  position: Query
  type: String
  description:
    zh: ""
  required: false
  hidden: true
- name: ResourceOwnerId
  position: Query
  type: Long
  description:
    zh: ""
  required: false
  hidden: true
- name: SyncMode
  position: Query
  type: String
  description:
    zh: Sync：强同步；Semi-sync：半同步；Async：异步。
  required: true
  hidden: false
- name: HAMode
  position: Query
  type: String
  description:
    zh: RPO：数据持久性优先；RTO：实例可用性优先。
  required: true
  hidden: false
- name: DbInstanceId
  position: Query
  type: String
  description:
    zh: 实例名。
  required: true
  hidden: false
- name: OwnerAccount
  position: Query
  type: String
  description:
    zh: 用户主账号。
  required: false
  hidden: true
