name: ModifyDBInstanceHAConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Action
  type: String
  required: false
  hidden: true
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: ResourceOwnerAccount
  type: String
  required: false
  hidden: true
  subparameters: []
- name: ResourceOwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: SyncMode
  type: String
  required: true
  hidden: false
  subparameters: []
- name: HAMode
  type: String
  required: true
  hidden: false
  subparameters: []
- name: DbInstanceId
  type: String
  required: true
  hidden: false
  subparameters: []
- name: OwnerAccount
  type: String
  required: false
  hidden: true
  subparameters: []
