name: DescribeMonitorValues
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Action
  type: String
  required: false
  hidden: true
  subparameters: []
- name: SecurityToken
  type: String
  required: false
  hidden: false
  subparameters: []
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: ResourceOwnerAccount
  type: String
  required: false
  hidden: true
  subparameters: []
- name: ResourceOwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: OwnerAccount
  type: String
  required: false
  hidden: true
  subparameters: []
- name: InstanceIds
  type: String
  required: false
  hidden: false
  subparameters: []
- name: MonitorKeys
  type: String
  required: false
  hidden: false
  subparameters: []
