name: GetEnterpriseConfig
parameters:
- name: RegionId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: SysFrom
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Operator
  type: String
  required: false
  hidden: false
  subparameters: []
