name: ProduceInstance
protocol: HTTP|HTTPS
method: POST|GET
description: {}
document_id: ""
parameters:
- name: RegionId
  position: Query
  type: String
  required: false
  hidden: false
- name: TraceId
  position: Query
  type: String
  required: false
  hidden: false
- name: ProduceParameter
  position: Query
  type: String
  required: false
  hidden: false
