name: DescribeClusterServiceConfigHistory
parameters:
- name: ResourceOwnerId
  type: Long
  required: false
  subparameters: []
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: RegionId
  type: String
  required: true
  subparameters: []
- name: ClusterId
  type: String
  required: true
  subparameters: []
- name: ServiceName
  type: String
  required: true
  subparameters: []
- name: ConfigVersion
  type: String
  required: true
  subparameters: []
