name: ListClusterServiceConfigHistory
parameters:
- name: ResourceOwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: RegionId
  type: String
  required: true
  hidden: false
  subparameters: []
- name: ClusterId
  type: String
  required: true
  hidden: false
  subparameters: []
- name: ServiceName
  type: String
  required: false
  hidden: false
  subparameters: []
- name: ConfigVersion
  type: String
  required: false
  hidden: false
  subparameters: []
- name: PageNumber
  type: Integer
  required: false
  hidden: false
  subparameters: []
- name: PageSize
  type: Integer
  required: false
  hidden: false
  subparameters: []
