name: ConfigDdos
parameters:
- name: InstanceId
  type: String
  required: true
  subparameters: []
- name: InstanceType
  type: String
  required: false
  subparameters: []
- name: FlowPosition
  type: Integer
  required: true
  subparameters: []
- name: StrategyPosition
  type: Integer
  required: true
  subparameters: []
- name: Level
  type: Integer
  required: true
  subparameters: []
