name: GetConfig
parameters:
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: InstanceId
  type: String
  required: true
  subparameters: []
- name: Name
  type: String
  required: true
  subparameters: []
- name: ObjectId
  type: String
  required: false
  subparameters: []
- name: ObjectType
  type: String
  required: true
  subparameters: []
