name: SetAuthConfig
parameters:
- name: Action
  type: String
  required: false
  subparameters: []
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: OwnerId
  type: String
  required: false
  subparameters: []
- name: ResourceOwnerId
  type: String
  required: false
  subparameters: []
- name: ResourceOwnerAccount
  type: String
  required: false
  subparameters: []
- name: OwnerAccount
  type: String
  required: false
  subparameters: []
- name: Key1
  type: String
  required: false
  subparameters: []
- name: Key2
  type: String
  required: false
  subparameters: []
