name: GetSnapshotSettings
parameters:
- name: AccessKeyId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: Action
  type: String
  required: false
  hidden: true
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: ResourceOwnerAccount
  type: String
  required: false
  hidden: true
  subparameters: []
- name: ResourceOwnerId
  type: Long
  required: false
  hidden: true
  subparameters: []
- name: OwnerAccount
  type: String
  required: false
  hidden: true
  subparameters: []
- name: RegionId
  type: String
  required: false
  hidden: false
  subparameters: []
- name: InstanceId
  type: String
  required: true
  hidden: false
  subparameters: []
