name: SetSnapshotSettings
parameters:
- name: AccessKeyId
  type: String
  required: false
  subparameters: []
- name: Action
  type: String
  required: false
  subparameters: []
- name: OwnerId
  type: Long
  required: false
  subparameters: []
- name: ResourceOwnerAccount
  type: String
  required: false
  subparameters: []
- name: ResourceOwnerId
  type: Long
  required: false
  subparameters: []
- name: OwnerAccount
  type: String
  required: false
  subparameters: []
- name: RegionId
  type: String
  required: false
  subparameters: []
- name: InstanceId
  type: String
  required: true
  subparameters: []
- name: BeginHour
  type: Integer
  required: false
  subparameters: []
- name: EndHour
  type: Integer
  required: false
  subparameters: []
- name: RetentionDay
  type: Integer
  required: false
  subparameters: []
- name: MaxAutoSnapshots
  type: Integer
  required: false
  subparameters: []
- name: MaxManualSnapshots
  type: Integer
  required: false
  subparameters: []
- name: DayList
  type: Integer
  required: true
  subparameters: []
